
package jcreepy.protocol.codec;

import jcreepy.network.Packet;
import jcreepy.network.codec.CodecLookupService;
import jcreepy.network.codec.PacketCodec;
import jcreepy.protocol.codec.auth.EncKeyRequestCodec;
import jcreepy.protocol.codec.auth.EncKeyResponseCodec;
import jcreepy.protocol.codec.entity.EntityActionCodec;
import jcreepy.protocol.codec.entity.EntityAnimationCodec;
import jcreepy.protocol.codec.entity.EntityAttachEntityCodec;
import jcreepy.protocol.codec.entity.EntityDestroyCodec;
import jcreepy.protocol.codec.entity.EntityEquipmentCodec;
import jcreepy.protocol.codec.entity.EntityInitializeCodec;
import jcreepy.protocol.codec.entity.EntityInteractCodec;
import jcreepy.protocol.codec.entity.EntityItemDataCodec;
import jcreepy.protocol.codec.entity.EntityMetadataCodec;
import jcreepy.protocol.codec.entity.EntityRelativePositionCodec;
import jcreepy.protocol.codec.entity.EntityStatusCodec;
import jcreepy.protocol.codec.entity.EntityTileDataCodec;
import jcreepy.protocol.codec.entity.effect.EntityEffectCodec;
import jcreepy.protocol.codec.entity.effect.EntityRemoveEffectCodec;
import jcreepy.protocol.codec.entity.pos.EntityHeadYawCodec;
import jcreepy.protocol.codec.entity.pos.EntityRelativePositionYawCodec;
import jcreepy.protocol.codec.entity.pos.EntityTeleportCodec;
import jcreepy.protocol.codec.entity.pos.EntityVelocityCodec;
import jcreepy.protocol.codec.entity.pos.EntityYawCodec;
import jcreepy.protocol.codec.entity.spawn.EntityExperienceOrbCodec;
import jcreepy.protocol.codec.entity.spawn.EntityItemCodec;
import jcreepy.protocol.codec.entity.spawn.EntityMobCodec;
import jcreepy.protocol.codec.entity.spawn.EntityPaintingCodec;
import jcreepy.protocol.codec.entity.spawn.EntitySpawnObjectCodec;
import jcreepy.protocol.codec.entity.spawn.EntityThunderboltCodec;
import jcreepy.protocol.codec.player.PlayerAbilityCodec;
import jcreepy.protocol.codec.player.PlayerBedCodec;
import jcreepy.protocol.codec.player.PlayerBlockPlacementCodec;
import jcreepy.protocol.codec.player.PlayerChatCodec;
import jcreepy.protocol.codec.player.PlayerCollectItemCodec;
import jcreepy.protocol.codec.player.PlayerDiggingCodec;
import jcreepy.protocol.codec.player.PlayerExperienceCodec;
import jcreepy.protocol.codec.player.PlayerGameStateCodec;
import jcreepy.protocol.codec.player.PlayerGroundCodec;
import jcreepy.protocol.codec.player.PlayerHealthCodec;
import jcreepy.protocol.codec.player.PlayerHeldItemChangeCodec;
import jcreepy.protocol.codec.player.PlayerLocaleViewDistanceCodec;
import jcreepy.protocol.codec.player.PlayerSoundEffectCodec;
import jcreepy.protocol.codec.player.PlayerStatisticCodec;
import jcreepy.protocol.codec.player.PlayerStatusCodec;
import jcreepy.protocol.codec.player.PlayerTabCompleteCodec;
import jcreepy.protocol.codec.player.PlayerTimeCodec;
import jcreepy.protocol.codec.player.conn.PlayerHandshakeCodec;
import jcreepy.protocol.codec.player.conn.PlayerKickCodec;
import jcreepy.protocol.codec.player.conn.PlayerListCodec;
import jcreepy.protocol.codec.player.conn.PlayerLoginRequestCodec;
import jcreepy.protocol.codec.player.conn.PlayerPingCodec;
import jcreepy.protocol.codec.player.pos.PlayerPositionCodec;
import jcreepy.protocol.codec.player.pos.PlayerPositionYawCodec;
import jcreepy.protocol.codec.player.pos.PlayerRespawnCodec;
import jcreepy.protocol.codec.player.pos.PlayerSpawnCodec;
import jcreepy.protocol.codec.player.pos.PlayerSpawnPositionCodec;
import jcreepy.protocol.codec.player.pos.PlayerYawCodec;
import jcreepy.protocol.codec.server.ServerListPingCodec;
import jcreepy.protocol.codec.server.ServerPluginCodec;
import jcreepy.protocol.codec.window.WindowClickCodec;
import jcreepy.protocol.codec.window.WindowCloseCodec;
import jcreepy.protocol.codec.window.WindowCreativeActionCodec;
import jcreepy.protocol.codec.window.WindowEnchantItemCodec;
import jcreepy.protocol.codec.window.WindowItemsCodec;
import jcreepy.protocol.codec.window.WindowOpenCodec;
import jcreepy.protocol.codec.window.WindowPropertyCodec;
import jcreepy.protocol.codec.window.WindowSlotCodec;
import jcreepy.protocol.codec.window.WindowTransactionCodec;
import jcreepy.protocol.codec.world.EffectCodec;
import jcreepy.protocol.codec.world.ExplosionCodec;
import jcreepy.protocol.codec.world.block.BlockActionCodec;
import jcreepy.protocol.codec.world.block.BlockBreakAnimationCodec;
import jcreepy.protocol.codec.world.block.BlockBulkCodec;
import jcreepy.protocol.codec.world.block.BlockChangeCodec;
import jcreepy.protocol.codec.world.block.SignCodec;
import jcreepy.protocol.codec.world.chunk.ChunkBulkCodec;
import jcreepy.protocol.codec.world.chunk.ChunkDataCodec;

public class MinecraftCodecLookupService
extends CodecLookupService {
    public static final MinecraftCodecLookupService INSTANCE = new MinecraftCodecLookupService();

    public MinecraftCodecLookupService() {
        try {
            this.bind(PlayerPingCodec.class);
            this.bind(PlayerLoginRequestCodec.class);
            this.bind(PlayerHandshakeCodec.class);
            this.bind(PlayerChatCodec.class);
            this.bind(PlayerTimeCodec.class);
            this.bind(EntityEquipmentCodec.class);
            this.bind(PlayerSpawnPositionCodec.class);
            this.bind(EntityInteractCodec.class);
            this.bind(PlayerHealthCodec.class);
            this.bind(PlayerRespawnCodec.class);
            this.bind(PlayerGroundCodec.class);
            this.bind(PlayerPositionCodec.class);
            this.bind(PlayerYawCodec.class);
            this.bind(PlayerPositionYawCodec.class);
            this.bind(PlayerDiggingCodec.class);
            this.bind(PlayerBlockPlacementCodec.class);
            this.bind(PlayerHeldItemChangeCodec.class);
            this.bind(PlayerBedCodec.class);
            this.bind(EntityAnimationCodec.class);
            this.bind(EntityActionCodec.class);
            this.bind(PlayerSpawnCodec.class);
            this.bind(EntityItemCodec.class);
            this.bind(PlayerCollectItemCodec.class);
            this.bind(EntitySpawnObjectCodec.class);
            this.bind(EntityMobCodec.class);
            this.bind(EntityPaintingCodec.class);
            this.bind(EntityExperienceOrbCodec.class);
            this.bind(EntityVelocityCodec.class);
            this.bind(EntityDestroyCodec.class);
            this.bind(EntityInitializeCodec.class);
            this.bind(EntityRelativePositionCodec.class);
            this.bind(EntityYawCodec.class);
            this.bind(EntityRelativePositionYawCodec.class);
            this.bind(EntityTeleportCodec.class);
            this.bind(EntityHeadYawCodec.class);
            this.bind(EntityStatusCodec.class);
            this.bind(EntityAttachEntityCodec.class);
            this.bind(EntityMetadataCodec.class);
            this.bind(EntityEffectCodec.class);
            this.bind(EntityRemoveEffectCodec.class);
            this.bind(PlayerExperienceCodec.class);
            this.bind(ChunkDataCodec.class);
            this.bind(BlockBulkCodec.class);
            this.bind(BlockChangeCodec.class);
            this.bind(BlockActionCodec.class);
            this.bind(BlockBreakAnimationCodec.class);
            this.bind(ChunkBulkCodec.class);
            this.bind(ExplosionCodec.class);
            this.bind(EffectCodec.class);
            this.bind(PlayerSoundEffectCodec.class);
            this.bind(PlayerGameStateCodec.class);
            this.bind(EntityThunderboltCodec.class);
            this.bind(WindowOpenCodec.class);
            this.bind(WindowCloseCodec.class);
            this.bind(WindowClickCodec.class);
            this.bind(WindowSlotCodec.class);
            this.bind(WindowItemsCodec.class);
            this.bind(WindowPropertyCodec.class);
            this.bind(WindowTransactionCodec.class);
            this.bind(WindowCreativeActionCodec.class);
            this.bind(WindowEnchantItemCodec.class);
            this.bind(SignCodec.class);
            this.bind(EntityItemDataCodec.class);
            this.bind(EntityTileDataCodec.class);
            this.bind(PlayerStatisticCodec.class);
            this.bind(PlayerListCodec.class);
            this.bind(PlayerAbilityCodec.class);
            this.bind(PlayerTabCompleteCodec.class);
            this.bind(PlayerLocaleViewDistanceCodec.class);
            this.bind(PlayerStatusCodec.class);
            this.bind(ServerPluginCodec.class);
            this.bind(EncKeyResponseCodec.class);
            this.bind(EncKeyRequestCodec.class);
            this.bind(ServerListPingCodec.class);
            this.bind(PlayerKickCodec.class);
        }
        catch (Exception ex) {
            throw new ExceptionInInitializerError(ex);
        }
    }
}

